// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7Ism8r-0gZPT-H-kwzmoU3TwNWo1i4w',
    appId: '1:254268454293:web:23ca02bc3ac0b0c4d2b29c',
    messagingSenderId: '254268454293',
    projectId: 'kpps-efeaf',
    authDomain: 'kpps-efeaf.firebaseapp.com',
    storageBucket: 'kpps-efeaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QJu3nFjSe2khKVL5iTJNTiEq0iiQ-XQ',
    appId: '1:254268454293:android:8ac5bc57267160f0d2b29c',
    messagingSenderId: '254268454293',
    projectId: 'kpps-efeaf',
    storageBucket: 'kpps-efeaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDik--Zq3sfVZ8Oo5ZerWRr20qSexKgmdY',
    appId: '1:254268454293:ios:da1012278fdf6140d2b29c',
    messagingSenderId: '254268454293',
    projectId: 'kpps-efeaf',
    storageBucket: 'kpps-efeaf.firebasestorage.app',
    iosBundleId: 'com.example.kpps',
  );
}
